#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_PATH="${CONFIG_PATH:-${SCRIPT_DIR}/../config/runtime_defaults.json}"

config_value() {
  python3 - "$CONFIG_PATH" "$1" "$2" <<'PY'
import json
import sys
from pathlib import Path

config_path = Path(sys.argv[1])
section = sys.argv[2]
key = sys.argv[3]
payload = json.loads(config_path.read_text(encoding="utf-8"))
print(payload.get(section, {}).get(key, ""))
PY
}

prompt_value() {
  local var_name="$1"
  local prompt_label="$2"
  local default_value="$3"
  local current_value="${!var_name:-$default_value}"
  local response=""
  if [[ -n "${current_value}" ]]; then
    read -r -p "${prompt_label} [${current_value}]: " response
    response="${response:-$current_value}"
  else
    read -r -p "${prompt_label}: " response
  fi
  printf -v "${var_name}" '%s' "${response}"
}

prompt_secret() {
  local var_name="$1"
  local prompt_label="$2"
  local current_value="${!var_name:-}"
  local response=""
  if [[ -n "${current_value}" ]]; then
    read -r -s -p "${prompt_label} [press Enter to keep current value]: " response
    echo
    response="${response:-$current_value}"
  else
    read -r -s -p "${prompt_label}: " response
    echo
  fi
  printf -v "${var_name}" '%s' "${response}"
}

REMOTE_HOST="${RADAR_REMOTE_HOST:-${REMOTE_HOST:-$(config_value deployment server_host)}}"
SMTP_ENV_FILE="${SMTP_ENV_FILE:-$(config_value email_delivery smtp_env_file)}"
DEFAULT_EMAIL_TO="$(config_value email_delivery email_to)"

if [[ -z "${SMTP_ENV_FILE}" ]]; then
  SMTP_ENV_FILE="/opt/quant-runtime/config/paper_trade_daily.env"
fi
if [[ -z "${REMOTE_HOST}" ]]; then
  echo "Missing remote host. Set RADAR_REMOTE_HOST or REMOTE_HOST in a private, untracked environment." >&2
  exit 2
fi

echo "Configuring Radar Daily SMTP delivery on ${REMOTE_HOST}"
echo "Remote env file: ${SMTP_ENV_FILE}"
echo

prompt_value SMTP_HOST "SMTP host" "${SMTP_HOST:-}"
prompt_value SMTP_PORT "SMTP port" "${SMTP_PORT:-587}"
prompt_value SMTP_USERNAME "SMTP username" "${SMTP_USERNAME:-}"
prompt_secret SMTP_PASSWORD "SMTP password or app password"
prompt_value SMTP_FROM "SMTP from address" "${SMTP_FROM:-${SMTP_USERNAME:-}}"
prompt_value SMTP_TO "Default recipient list" "${SMTP_TO:-${DEFAULT_EMAIL_TO}}"
prompt_value SMTP_FROM_NAME "Optional sender display name" "${SMTP_FROM_NAME:-Radar Daily Report}"
prompt_value SMTP_REPLY_TO "Optional reply-to address" "${SMTP_REPLY_TO:-}"
prompt_value SMTP_STARTTLS "Use STARTTLS (1/0)" "${SMTP_STARTTLS:-1}"
prompt_value SMTP_USE_SSL "Use implicit SSL (1/0)" "${SMTP_USE_SSL:-0}"

tmp_env="$(mktemp)"
trap 'rm -f "${tmp_env}"' EXIT

export SMTP_HOST SMTP_PORT SMTP_USERNAME SMTP_PASSWORD SMTP_FROM SMTP_TO SMTP_FROM_NAME SMTP_REPLY_TO SMTP_STARTTLS SMTP_USE_SSL
python3 - "${tmp_env}" <<'PY'
import os
import shlex
import sys
from pathlib import Path

path = Path(sys.argv[1])
keys = [
    "SMTP_HOST",
    "SMTP_PORT",
    "SMTP_USERNAME",
    "SMTP_PASSWORD",
    "SMTP_FROM",
    "SMTP_TO",
    "SMTP_FROM_NAME",
    "SMTP_REPLY_TO",
    "SMTP_STARTTLS",
    "SMTP_USE_SSL",
]
lines = [
    "# Generated by install_radar_daily_smtp_env.sh",
    "# Keep this file only on the remote host. It contains SMTP secrets.",
]
for key in keys:
    value = os.environ.get(key, "")
    if value == "":
        continue
    lines.append(f"{key}={shlex.quote(value)}")
path.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY

ssh "${REMOTE_HOST}" "mkdir -p '$(dirname "${SMTP_ENV_FILE}")'"
scp "${tmp_env}" "${REMOTE_HOST}:${SMTP_ENV_FILE}"
ssh "${REMOTE_HOST}" "chmod 600 '${SMTP_ENV_FILE}'"

echo
echo "Remote SMTP env installed at ${REMOTE_HOST}:${SMTP_ENV_FILE}"
echo "Test it with:"
echo "  ssh ${REMOTE_HOST} \"source /opt/industry-signal-radar/.venv/bin/activate && python /opt/industry-signal-radar/scripts/send_radar_daily_report_email.py --config /opt/industry-signal-radar/config/runtime_defaults.json --report-transport local --smtp-env-file '${SMTP_ENV_FILE}' --dry-run\""
